### ISSUE TITLE
Convert Table

### ISSUE THREAD

**Issue by SchumacherFM** [Machiel/slugify#2]
Would love to see such a convert table being implemented:

https://github.com/magento/magento2/blob/master/lib%2Finternal%2FMagento%2FFramework%2FFilter%2FTranslit.php#L20

Above PHP code comes in handy for `map[rune][rune]` :-)

**Comment by machiel** [comment]
Good point, will look into it :)

**Comment by machiel** [comment]
For PR see #3

**Comment by SchumacherFM** [comment]
Awesome! Thank you very much!
